services:
- type: web
  name: openai-8wk-sprint-api
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --app-dir app-api --host 0.0.0.0 --port $PORT
  envVars:
  - key: MOCK_MODE
    value: "1"
 codex/add-render.yaml-for-web-frontend-pmawb8
staticSites:
- name: openai-8wk-sprint-web

- type: static_site
  name: openai-8wk-sprint-web
  buildCommand: cd app-web && npm ci && npm run build
  staticPublishPath: app-web/dist
  envVars:
  - key: VITE_API_BASE
    value: https://openai-8wk-sprint-api.onrender.com
